### ISSUE TITLE
WHY ARE YOU USING APPIMAGE

### ISSUE THREAD

**Issue by mequidis** [roeyba/linux_commands#3]
there's probably a PPA

I will never stop stalking this repository

**Comment by roeyba** [comment]
long story, i didnt used it at the end

**Comment by roeyba** [comment]
btw I wanted to install tor(this is what the image was for), I was able to downlod it properly and for some reason it works very slow. do you know why?
I also have tor installed in my windows computer in the same local network and it works x3 faster

**Comment by roeyba** [comment]
האמת למה לא שלחתי לך בוואצאפ

**Comment by mequidis** [comment]
SEND ME THE DETAILS and I SHALL LOOK!

**Comment by mequidis** [comment]
btw I didn't know about dist-upgrade that's cool https://github.com/roeyba/linux_commands/commit/cd20ee6bea519d7472f6ca89865ca8618db62f85
